
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 16 14:31:23 CEST 2018
//----------------------------------------------------

package hassen.logo.compiler;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int UNARY_PLUS = 27;
  public static final int OPEN_PARENTHESIS = 25;
  public static final int OFF = 15;
  public static final int PEN = 10;
  public static final int FRAME = 4;
  public static final int DEFINE = 31;
  public static final int HOME = 5;
  public static final int CALL = 16;
  public static final int GOTO = 11;
  public static final int UNARY_MINUS = 28;
  public static final int ON = 14;
  public static final int UP = 6;
  public static final int END = 30;
  public static final int INK = 21;
  public static final int ID = 3;
  public static final int SUB = 18;
  public static final int RIGHT = 8;
  public static final int LEFT = 9;
  public static final int MULT = 19;
  public static final int NUMBER = 2;
  public static final int EOF = 0;
  public static final int SET = 24;
  public static final int DIV = 20;
  public static final int ADD = 17;
  public static final int SEP = 23;
  public static final int error = 1;
  public static final int TURN = 13;
  public static final int DOWN = 7;
  public static final int REPEAT = 29;
  public static final int CLOSE_PARENTHESIS = 26;
  public static final int TERM = 22;
  public static final int MOVE = 12;
}

