
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 16 14:31:24 CEST 2018
//----------------------------------------------------

package hassen.logo.interpreter;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int OFF = 7;
  public static final int USUB = 15;
  public static final int EQUAL = 10;
  public static final int HOME = 8;
  public static final int GOTO = 9;
  public static final int ON = 6;
  public static final int END = 17;
  public static final int VARIABLE = 19;
  public static final int SUB = 12;
  public static final int COMA = 3;
  public static final int MULT = 13;
  public static final int EOF = 0;
  public static final int DIV = 14;
  public static final int ADD = 11;
  public static final int error = 1;
  public static final int TURN = 5;
  public static final int INTEGER = 18;
  public static final int REPEAT = 16;
  public static final int TERM = 2;
  public static final int MOVE = 4;
}

